### ISSUE TITLE
Running Error!

### ISSUE THREAD

**Issue by Anthonyyouny** [yardenas/la-mbda#1]
Hi, 
  I'm trying to reproduce the code. However, I got the following error when I run the exactly same command as yours.

---
Traceback (most recent call last):                                                                                                                                                                                   
  File "experiments/train.py", line 7, in <module>
    train_utils.train(config, LAMBDA)
  File "/root/lambda/la-mbda/experiments/train_utils.py", line 139, in train
    on_episode_end=lambda episode_summary, steps_count: on_episode_end(
  File "/root/lambda/la-mbda/la_mbda/utils.py", line 101, in interact
    pbar, len(episodes) < config.render_episodes and not training)
  File "/root/lambda/la-mbda/la_mbda/utils.py", line 68, in do_episode
    action = agent(observation, training)
  File "/root/lambda/la-mbda/la_mbda/la_mbda.py", line 39, in __call__
    self.pretrain_model()
  File "/root/lambda/la-mbda/la_mbda/la_mbda.py", line 85, in pretrain_model
    self.model.train(batch)
  File "/root/lambda/la-mbda/la_mbda/bayesian_world_model.py", line 26, in train
    posterior_beliefs = self._training_step(batch)
  File "/opt/conda/envs/lambda/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/envs/lambda/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/opt/conda/envs/lambda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/opt/conda/envs/lambda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/opt/conda/envs/lambda/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/opt/conda/envs/lambda/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found:  No algorithm worked!
	 [[node sequential_1/conv2d/Conv2D (defined at /root/lambda/la-mbda/la_mbda/building_blocks.py:62) ]]
	 [[SWAG/SWAG/update_7/StatefulPartitionedCall/cond_1/pivot_t/_2025/_295]]
  (1) Not found:  No algorithm worked!
	 [[node sequential_1/conv2d/Conv2D (defined at /root/lambda/la-mbda/la_mbda/building_blocks.py:62) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference__training_step_35978]

Errors may have originated from an input operation.
Input Source operations connected to node sequential_1/conv2d/Conv2D:
 Reshape (defined at /root/lambda/la-mbda/la_mbda/building_blocks.py:61)

Input Source operations connected to node sequential_1/conv2d/Conv2D:
 Reshape (defined at /root/lambda/la-mbda/la_mbda/building_blocks.py:61)

Function call stack:
_training_step -> _training_step

 20%|##################################                                                                                                                                        | 5000/25000 [01:25<05:42, 58.36it/s]

---

Any ideas? Thanks a lot!!!

**Comment by Anthonyyouny** [comment]
I have fixed the bug by myself. Sorry for bothering!!

**Comment by yardenas** [comment]
Hi! 
Really happy that you're trying to reproduce the experiments!

I didn't encounter this error on my system before, what was the issue and how did you fix it? If it's something crucial we can open a pull request; let me know.

**Comment by Anthonyyouny** [comment]
Hi!
The bug seems to be related with CUDA 11.0 on RTX 2070 Super card. I have fixed the bug by the suggestion in [here](https://github.com/tensorflow/tensorflow/issues/43174).

By the way, I have successfully re-produced the results on PointGoal2! However, I found that the algorithm runs too slowly (2 days +), especially in the second half of the total training steps. Do you have any suggestions to speed up it?

device: NVIDIA GeForce RTX 3090

**Comment by yardenas** [comment]
> By the way, I have successfully re-produced the results on PointGoal2!

Awesome! :)

> However, I found that the algorithm runs too slowly (2 days +), especially in the second half of the total training steps. Do you have any suggestions to speed up it?

I'm running it on a GeForceRTX2080Ti and it takes slightly less than 24 hours to finish 1M steps.

There are two main bottlenecks that I'm aware of:
1. Data loading from the replay buffer. You could try to tune the ```buffer_size``` [here](https://github.com/yardenas/la-mbda/blob/d2fff2aeeb2bc4f3779500030b9bd83a81127cdf/la_mbda/replay_buffer.py#L72).
2. Another option is to use less model posterior samples or smaller batch size. For instance ```--posterior_samples 1``` would use only one posterior sample so the algorithm would not use pessimism and optimism (this affects the results). For a batch size of 16, add ```--batch_size 16``` to your command; again this could potentially affect the results.
Good luck!
