### ISSUE TITLE
Issue with mujoco210 build

### ISSUE THREAD

**Issue by SimonZhan-code** [yardenas/la-mbda#7]
Hi! Since MuJoCo200 is no longer available, I'm trying to build the environment by using MuJoCo210 and dm-control 1.0.1. However, I met the following problem. Is there any solution to get pass this? I have attached my environment packages and error report below.  

`
Traceback (most recent call last):
  File "experiments/train.py", line 7, in <module>
    train_utils.train(config, LAMBDA)
  File "/home/simonzhan/Desktop/Projects/la-mbda/experiments/train_utils.py", line 137, in train
    training_steps, training_episodes_summaries = utils.interact(
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/la_mbda/utils.py", line 101, in interact
    do_episode(agent, training,
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/la_mbda/utils.py", line 63, in do_episode
    observation = environment.reset() if reset_function is None else reset_function()
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/core.py", line 337, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/core.py", line 283, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 26, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/Desktop/Projects/la-mbda/safety-gym-dm_hack/safety_gym/envs/engine.py", line 897, in reset
    self.build()
  File "/home/simonzhan/Desktop/Projects/la-mbda/safety-gym-dm_hack/safety_gym/envs/engine.py", line 871, in build
    self.world.reset()
  File "/home/simonzhan/Desktop/Projects/la-mbda/safety-gym-dm_hack/safety_gym/envs/world.py", line 317, in reset
    self.build()
  File "/home/simonzhan/Desktop/Projects/la-mbda/safety-gym-dm_hack/safety_gym/envs/world.py", line 292, in build
    self.sim = dm_control.mujoco.Physics.from_xml_string(self.xml_string)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 424, in from_xml_string
    return cls.from_model(model)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 407, in from_model
    return cls(data)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 122, in __init__
    self._reload_from_data(data)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 389, in _reload_from_data
    data=index.struct_indexer(self.data, 'mjdata', axis_indexers),)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/dm_control/mujoco/index.py", line 623, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjData' object has no attribute 'qacc_unc'
`

**Comment by SimonZhan-code** [comment]
Sorry, I fix this issue by updating dm-control to the most current version, and it turns out I'm using the most recent version of MuJoCo, not the 2.1.* version I imagined. However, I met the following error:
`Traceback (most recent call last):
  File "experiments/train.py", line 7, in <module>
    train_utils.train(config, LAMBDA)
  File "/home/simonzhan/Desktop/Projects/la-mbda/experiments/train_utils.py", line 137, in train
    training_steps, training_episodes_summaries = utils.interact(
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/la_mbda/utils.py", line 99, in interact
    do_episode(agent, training,
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/la_mbda/utils.py", line 63, in do_episode
    observation = environment.reset() if reset_function is None else reset_function()
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/core.py", line 311, in reset
    return self.observation(self.env.reset(**kwargs))
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/core.py", line 337, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/core.py", line 283, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 26, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/anaconda3/envs/lambda-advanced/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/simonzhan/Desktop/Projects/la-mbda/safety-gym-dm_hack/safety_gym/envs/engine.py", line 908, in reset
    return self.obs()
  File "/home/simonzhan/Desktop/Projects/la-mbda/safety-gym-dm_hack/safety_gym/envs/engine.py", line 1140, in obs
    assert self.observation_space.contains(obs), f'Bad obs {obs} {self.observation_space}'
` 
`
AssertionError: Bad obs [0.00000000e+00 0.00000000e+00 9.81000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.10617833e-01 7.57387519e-01 4.46769686e-01 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.17173136e-01 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.62045643e-01 6.47385634e-01 5.58122557e-01 5.04178798e-01
 2.73862809e-01 4.08909418e-01 5.70473492e-01 7.06539924e-01
 5.88646463e-01 8.05819599e-01 1.37104973e-01 4.80834926e-01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.33242627e-01
 2.39863573e-01 6.62094583e-03 0.00000000e+00 0.00000000e+00
0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00] Box(-inf, inf, (60,), float32)
`

After comment out the line 1140 in `safety-gym-dm_hack/safety-gym/envs/engine`, the code seems up and running, but I'm not sure does it make sense or not?

**Comment by yardenas** [comment]
Hey!
Regarding the second comment, I've seen this issue before already. The error occurs because of a validation that gym did not have when I was working on lambda. 

Btw, I have a jax implementation [here](https://github.com/yardenas/safe-adaptation-agents/tree/main/safe_adaptation_agents%2Fagents%2Fmodel_based).

Cheers 🫡

**Comment by SimonZhan-code** [comment]
Thx man! I will check it out!
